-- Esercitazione 1

-- Query 1
SELECT * 
FROM DELIVERERS;

-- Query 2
SELECT DISTINCT COMPANYID
FROM COMPANYDEL;

-- Query 3
SELECT NAME, DELIVERERID
FROM DELIVERERS
WHERE NAME LIKE 'B%';

-- Query 4
SELECT NAME, SEX, DELIVERERID
FROM DELIVERERS
WHERE PHONENO <> 8467 OR PHONENO IS NULL;

-- Query 5
SELECT DISTINCT NAME, TOWN
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID;

-- Query 6
SELECT DISTINCT NAME, INITIALS
FROM DELIVERERS D, PENALTIES P, COMPANIES C 
WHERE D.DELIVERERID = C.DELIVERERID AND
      C.DELIVERERID = P.DELIVERERID AND
      DATA > TO_DATE('31/12/1980', 'DD/MM/YYYY')
ORDER BY NAME;

-- Query 7
SELECT C.COMPANYID, D.DELIVERERID
FROM DELIVERERS D, COMPANYDEL C
WHERE C.DELIVERERID = D.DELIVERERID AND
      TOWN = 'Stratford' AND
      C.NUMDELIVERIES >= 1 AND
      C.NUMCOLLECTIONS >= 2;

-- Query 8
SELECT DISTINCT D.DELIVERERID
FROM DELIVERERS D, COMPANIES C, COMPANYDEL CD
WHERE D.DELIVERERID = CD.DELIVERERID AND
      CD.COMPANYID = C.COMPANYID AND
      D.YEAR_OF_BIRTH > 1962 AND
      C.MANDATE = 'first'
ORDER BY D.DELIVERERID DESC;

-- Query 9
SELECT DISTINCT D.NAME
FROM DELIVERERS D, COMPANYDEL C
WHERE D.DELIVERERID = C.DELIVERERID AND
      (D.TOWN = 'Inglewood' OR D.TOWN = 'Stratford')
GROUP BY C.DELIVERERID, D.NAME
HAVING COUNT(*) >= 2;

-- Query 10
SELECT P.DELIVERERID, SUM(P.AMOUNT)
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID AND
      D.TOWN = 'Inglewood'
GROUP BY P.DELIVERERID
HAVING COUNT(*) > 1;

-- Query 11
SELECT D.NAME, MIN(P.AMOUNT)
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID
GROUP BY P.DELIVERERID, D.NAME
HAVING COUNT(*) >= 2 AND COUNT(*) <= 4;

-- Query 12
SELECT SUM(C.NUMDELIVERIES), SUM(C.NUMCOLLECTIONS) 
FROM DELIVERERS D, COMPANYDEL C
WHERE D.DELIVERERID = C.DELIVERERID AND
      D.TOWN <> 'Stratford' AND
      D.NAME LIKE 'B%';
