-- Esercitazione 2

-- Query 1
SELECT D.DELIVERERID, D.NAME, D.INITIALS
FROM DELIVERERS D
WHERE D.DELIVERERID NOT IN (SELECT P.DELIVERERID
                            FROM PENALTIES P);

SELECT D.DELIVERERID, D.NAME, D.INITIALS
FROM DELIVERERS D
WHERE NOT EXISTS (SELECT * 
                  FROM PENALTIES P
                  WHERE D.DELIVERERID=P.DELIVERERID);

-- Query 2
SELECT DISTINCT DELIVERERID
FROM PENALTIES
WHERE AMOUNT=25 
      AND 
      DELIVERERID IN (SELECT DELIVERERID
                      FROM PENALTIES
                      WHERE AMOUNT=30);

SELECT DISTINCT P1.DELIVERERID
FROM PENALTIES P1
WHERE P1.AMOUNT=25 
      AND 
      EXISTS (SELECT *
              FROM PENALTIES P2
              WHERE P1.DELIVERERID=P2.DELIVERERID AND P2.AMOUNT=30);

SELECT DISTINCT DELIVERERID
FROM PENALTIES
WHERE DELIVERERID IN (SELECT DELIVERERID
                      FROM PENALTIES
                      WHERE AMOUNT=25)
      AND
      DELIVERERID IN (SELECT DELIVERERID
                      FROM PENALTIES
                      WHERE AMOUNT=30);

SELECT DISTINCT P.DELIVERERID
FROM PENALTIES P
WHERE EXISTS (SELECT *
              FROM PENALTIES P1
              WHERE P.DELIVERERID=P1.DELIVERERID AND P1.AMOUNT=25)
      AND
      EXISTS (SELECT *
              FROM PENALTIES P2
              WHERE P.DELIVERERID=P2.DELIVERERID AND P2.AMOUNT=30);
      
SELECT P1.DELIVERERID
FROM PENALTIES P1
WHERE P1.AMOUNT=25
INTERSECT
SELECT P2.DELIVERERID
FROM PENALTIES P2
WHERE P2.AMOUNT=30;

-- Query 3
SELECT DISTINCT D.DELIVERERID, D.NAME
FROM DELIVERERS D
WHERE D.DELIVERERID IN (SELECT P.DELIVERERID
                        FROM PENALTIES P
                        GROUP BY P.DATA, P.DELIVERERID
                        HAVING COUNT(*)>1);

SELECT DISTINCT D.DELIVERERID, D.NAME
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID=P.DELIVERERID
GROUP BY D.DELIVERERID, D.NAME, P.DATA
HAVING COUNT(*)>1;

-- Query 4
SELECT DELIVERERID
FROM COMPANYDEL
GROUP BY DELIVERERID
HAVING COUNT(*)=(SELECT COUNT(*)
                 FROM COMPANIES);

-- Query 5
SELECT DISTINCT DELIVERERID
FROM COMPANYDEL
WHERE COMPANYID IN (SELECT COMPANYID
                    FROM COMPANYDEL
                    WHERE DELIVERERID=57)
      AND DELIVERERID<>57; 

-- Query 6
SELECT D.DELIVERERID, D.NAME
FROM DELIVERERS D
WHERE (SELECT COUNT(*)
       FROM PENALTIES P1
       WHERE D.DELIVERERID=P1.DELIVERERID
             AND 
             P1.DATA>=TO_DATE('01/01/1980','DD/MM/YYYY')
             AND
             P1.DATA<=TO_DATE('31/12/1980','DD/MM/YYYY'))
      >
      (SELECT COUNT(*)
       FROM PENALTIES P2
       WHERE D.DELIVERERID=P2.DELIVERERID
             AND 
             P2.DATA>=TO_DATE('01/01/1981','DD/MM/YYYY')
             AND
             P2.DATA<=TO_DATE('31/12/1981','DD/MM/YYYY'));
             
SELECT D.DELIVERERID, D.NAME
FROM DELIVERERS D, PENALTIES P1
WHERE D.DELIVERERID=P1.DELIVERERID
      AND 
      P1.DATA>=TO_DATE('01/01/1980','DD/MM/YYYY')
      AND
      P1.DATA<=TO_DATE('31/12/1980','DD/MM/YYYY')
GROUP BY D.DELIVERERID, D.NAME
HAVING COUNT(*)>(SELECT COUNT(*)
                 FROM PENALTIES P2
                 WHERE D.DELIVERERID=P2.DELIVERERID
                       AND
                       P2.DATA>=TO_DATE('01/01/1981','DD/MM/YYYY')
                       AND
                       P2.DATA<=TO_DATE('31/12/1981','DD/MM/YYYY'));

-- Query 7
SELECT DELIVERERID
FROM PENALTIES
GROUP BY DELIVERERID
HAVING COUNT(*)=(SELECT MAX(COUNT(*))
                 FROM PENALTIES
                 GROUP BY DELIVERERID);

SELECT DELIVERERID
FROM PENALTIES
GROUP BY DELIVERERID
HAVING COUNT(*)=(SELECT MAX(PENALTIESSUM)
                 FROM (SELECT DELIVERERID, COUNT(*) PENALTIESSUM
                       FROM PENALTIES
                       GROUP BY DELIVERERID) PENALTIESCOUNT);

-- Query 8
SELECT DELIVERERID
FROM COMPANYDEL
WHERE DELIVERERID<>57
      AND
      COMPANYID IN (SELECT COMPANYID
                    FROM COMPANYDEL
                    WHERE DELIVERERID=57)
GROUP BY DELIVERERID
HAVING COUNT(*)>=(SELECT COUNT(*)
                  FROM COMPANYDEL
                  WHERE DELIVERERID=57);

-- Query 9
SELECT DISTINCT DELIVERERID
FROM COMPANYDEL
WHERE DELIVERERID<>57
      AND
      DELIVERERID NOT IN (SELECT DELIVERERID
                          FROM COMPANYDEL
                          WHERE COMPANYID NOT IN (SELECT COMPANYID
                                                  FROM COMPANYDEL
                                                  WHERE DELIVERERID=57));

-- Query 10
SELECT DELIVERERID
FROM COMPANYDEL
WHERE DELIVERERID<>57
      AND
      DELIVERERID NOT IN (SELECT DELIVERERID
                          FROM COMPANYDEL
                          WHERE COMPANYID NOT IN (SELECT COMPANYID
                                                  FROM COMPANYDEL
                                                  WHERE DELIVERERID=57))
GROUP BY DELIVERERID
HAVING COUNT(*)=(SELECT COUNT(*)
                  FROM COMPANYDEL
                  WHERE DELIVERERID=57);