-- Esercitazione 3 (I parte)

-- Query 1
SELECT  DELIVERERID, MIN(DATA), MAX(DATA)
FROM PENALTIES P
GROUP BY DELIVERERID
HAVING COUNT(*)>=2;

-- Query 2
SELECT DELIVERERID, DATA, AMOUNT
FROM PENALTIES P1
WHERE P1.DATA = (SELECT MAX(DATA)
                 FROM PENALTIES P2
                 WHERE P1.DELIVERERID=P2.DELIVERERID);

-- Query 3
SELECT COMPANYID
FROM COMPANYDEL
GROUP BY COMPANYID
HAVING COUNT(*)>(SELECT 0.30*COUNT(*)
                 FROM DELIVERERS );
